services:
  php:
    image: serversideup/php:8.4-fpm-nginx
    ports:
      - 8000:8080
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db
      REDIS_HOST: redis
      RED_PROVIDER_PORTAL_BASE_URL: "https://redproviderportal:3000"
    depends_on:
      - db
      - redis

  horizon:
    image: serversideup/php:8.4-cli
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: ["php", "/var/www/html/artisan", "horizon"]
    environment:
      DB_HOST: db
      REDIS_HOST: redis
      RED_PROVIDER_PORTAL_BASE_URL: "https://redproviderportal:3000"
    depends_on:
      - db
      - redis

  scheduler:
    image: serversideup/php:8.4-cli
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: ["php", "/var/www/html/artisan", "schedule:work"]
    environment:
      DB_HOST: db
      REDIS_HOST: redis
      RED_PROVIDER_PORTAL_BASE_URL: "https://redproviderportal:3000"
    depends_on:
      - db
      - redis

  db:
    image: mysql:lts
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: '${DB_DATABASE}'
      # MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      # MYSQL_USER: '${DB_USERNAME}'
      # MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:8-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  redproviderportal:
    image: node:24-alpine
    working_dir: /app
    command: node ./redproviderportal.js
    ports:
      - 3000:3000
    volumes:
      - ./RedProviderPortal:/app

volumes:
  db_data:
  redis_data:

