services:
  php:
    image: serversideup/php:8.4-fpm-nginx
    ports:
      - 8000:8080
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db
      MAIL_HOST: mailpit
      REDIS_HOST: redis
      RED_PROVIDER_PORTAL_BASE_URL: "https://redproviderportal:3000"
    depends_on:
      - db
      - redis

  db:
    image: mysql:lts
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: '${DB_DATABASE}'
      # MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      # MYSQL_USER: '${DB_USERNAME}'
      # MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - 1025:1025
      - 8025:8025

  redproviderportal:
    image: node:22-alpine
    working_dir: /app
    command: node ./redproviderportal.js
    ports:
      - 3000:3000
    volumes:
      - ./RedProviderPortal:/app
    # environment:
    #   PORT: 3000
    # # Replace with a named network or TLS configuration as needed for your host/Postman

volumes:
  db_data:
  redis_data:

